// Generated by scripts/build-orbit-mod.mjs from the website audio manifest.
export const CLIPS = {
  "ambience.wildwood": {
    "asset": "assets/audio/ambience.wildwood.m4a",
    "gain": 0.385,
    "durationMs": 22000
  },
  "music.wildwood": {
    "asset": "assets/audio/music.wildwood.m4a",
    "gain": 0.56,
    "durationMs": 80000
  },
  "ambience.amberwood": {
    "asset": "assets/audio/ambience.amberwood.m4a",
    "gain": 0.3272,
    "durationMs": 22000
  },
  "music.amberwood": {
    "asset": "assets/audio/music.amberwood.m4a",
    "gain": 0.56,
    "durationMs": 80000
  },
  "ambience.inkwild": {
    "asset": "assets/audio/ambience.inkwild.m4a",
    "gain": 0.385,
    "durationMs": 22000
  },
  "music.inkwild": {
    "asset": "assets/audio/music.inkwild.m4a",
    "gain": 0.56,
    "durationMs": 80000
  },
  "effect.start": {
    "asset": "assets/audio/effect.start.m4a",
    "gain": 0.35,
    "durationMs": 600
  },
  "effect.flip": {
    "asset": "assets/audio/effect.flip.m4a",
    "gain": 0.21,
    "durationMs": 120
  },
  "effect.score": {
    "asset": "assets/audio/effect.score.m4a",
    "gain": 0.105,
    "durationMs": 400
  },
  "effect.death": {
    "asset": "assets/audio/effect.death.m4a",
    "gain": 0.35,
    "durationMs": 900
  },
  "effect.best": {
    "asset": "assets/audio/effect.best.m4a",
    "gain": 0.35,
    "durationMs": 900
  },
  "effect.select": {
    "asset": "assets/audio/effect.select.m4a",
    "gain": 0.35,
    "durationMs": 300
  },
  "effect.warn": {
    "asset": "assets/audio/effect.warn.m4a",
    "gain": 0.35,
    "durationMs": 400
  }
};
